#!/usr/bin/env python3
"""Generate the verifier's directed tests for the BupChip CPU, as .S files.

  vgen.py OUTDIR            writes OUTDIR/v_*.S and OUTDIR/iss.txt

Written independently of ../../s1/directed/ and the other tests here, from
the lists in docs/BUPCHIP_CORE.md ("Verification plan" and "ARMv4
behaviours that must be exact"). Each test uses the shared frame
../../s1/directed/common.inc (included by absolute path, so that
../isa/run_isa.sh can build the files where they are written) and folds its
results into r10 with MIX/MIXF, storing r10 to the signature after each
group, so that a test stays inside the 8 KiB signature. iss.txt lists the
tests that stay inside the subset ARMv4 and ARMv5 agree on: run_vfy.sh also
checks those against Unicorn. Every test runs in lockstep with the reference.

  v_shift   each shift type by register amounts 0, 1, 31, 32, 33, 64, 224,
            255, 256, 0x1f1, 0xffffff20 and 0x80000021, and by immediate 1
            and 31, LSL #0, LSR #32, ASR #32 and RRX, through MOV, MOVS,
            ADCS, RSCS, BICS, TEQ and CMN, with C (and the other flags) 0
            and 1, on ten values; scaled register offsets with LSR #32, ASR
            #32, RRX and ROR
  v_imm     rotated immediates through all 16 opcodes with S: rotation 0
            (C unchanged) against a non-zero rotation of the same value (C
            = bit 31), including 0 rotated; the same without S
  v_cond    each of the 16 NZCV values against the 15 conditions other than
            NV, for 14 classes: ALU with S, B, BL, BX, LDR, STR,
            LDRH/LDRSB/STRB, MUL/MLA, UMULL, LDM/STM with write-back, shift
            by register, MSR, MRS, LDR pc
  v_mul     MUL, MLA and UMULL on 12 x 12 corner values; the overlaps ARMv4
            defines (MUL Rd == Rs, Rm == Rs; MLA Rd == Rn; UMULL RdLo or
            RdHi == Rs); flags kept
  v_blk     LDM/STM in the four modes, with and without write-back, lists of
            1, 2, 3, 9 and 10 registers (base not in the list); push/pop;
            stmib sp without write-back
  v_deps1-5 each producer of a register (loads from RAM, ROM, the asset
            window and the peripheral, post-indexed too; ALU, MOVS with a
            register shift, MUL, MLA, UMULL low and high, LDM first and
            last, base write-back of LDR, LDRH and LDM; MRS) followed at
            once, and after one other instruction, by each consumer
            position (Rn, Rm, Rm shifted, Rs, Rm and Rn of a register
            shift, MUL Rm/Rs, MLA Rn, UMULL Rm, store data of one- and
            two-clock stores, STRH and STM data, CMP, MSR, the base of a
            load, a load with write-back, a store and an LDM, a register
            offset); BL's link used at once
  v_wb      Rd == Rn with write-back for every transfer size, pre and post
            index, immediate and register offset, up and down; Rm == Rn and
            Rd == Rm for loads; LDRT/STRT/LDRBT/STRBT
  v_align   LDR, LDRH, LDRSH, LDRB and LDRSB at byte offsets 0-7 from RAM,
            ROM, the asset window (and its last eight bytes) and the
            peripheral; STR and STRH at every offset, read back; an
            unaligned base with write-back
  v_blkx    LDM/STM with the base in the list: lowest, middle, highest and
            alone, all four modes, with and without write-back
  v_mmio    peripheral reads and writes under every NZCV and condition (a
            failed read of 0x04 must not pop, a failed write of 0x10 not
            push); register offsets, write-back of the base, byte and
            halfword stores, sub-word reads, a load into its own base, the
            last word of the window
  v_nv      the NV condition (never, on ARMv4) on every class, including
            encodings the core halts on when they execute
  v_unpred  MUL and MLA Rd == Rm, UMULL RdLo or RdHi == Rm: the ARM7TDMI's
            results (or a halt, which run.sh reports)
SPDX-License-Identifier: MIT
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
COMMON = os.path.normpath(os.path.join(HERE, "..", "..", "s1", "directed", "common.inc"))
CONDS = ["eq", "ne", "cs", "cc", "mi", "pl", "vs", "vc", "hi", "ls", "ge", "lt", "gt", "le", "al"]
RINIT = ("rinit:\t.word\t0x01010101, 0x02020202, 0x03030303, 0x04040404, 0x05050505, "
         "0x06060606, 0x07070707, 0x08080808, 0x09090909, 0x0e0e0e0e")


def pattern(off):
    """common.inc's data-area word at byte offset off."""
    return (0x83828180 + 0x04040404 * (off // 4)) & 0xffffffff


class T:
    """One test file: instructions, with a literal pool every so often."""

    def __init__(self, name, desc):
        self.name, self.n, self.lab = name, 0, 0
        self.lines = ["@ " + l for l in desc.strip().split("\n")]
        self.lines += ["@ Generated by vgen.py. SPDX-License-Identifier: MIT",
                       '#include "%s"' % COMMON, "\tSTART",
                       "\t.macro MIX reg", "\tadd\tr10, \\reg, r10, ror #27", "\t.endm",
                       "\t.macro MIXF", "\tmrs\tr9, cpsr", "\tadd\tr10, r9, r10, ror #27", "\t.endm",
                       "\tmov\tr10, #0"]
        self.tail = []

    def label(self):
        self.lab += 1
        return "L%d" % self.lab

    def e(self, *ins):
        for i in ins:
            if i.endswith(":"):
                self.lines.append(i)
            else:
                self.lines.append("\t" + i)
                self.n += 1
        if self.n > 200:
            self.pool()

    def pool(self):
        self.lines.append("\tPOOL")
        self.n = 0

    def sig(self):
        self.e("SIG\tr10")

    def text(self):
        return "\n".join(self.lines + ["\tSIG\tr10", "\tb\tvend", "\t.align\t2"] + self.tail +
                         ["vend:", "\tEND", ""])


def setf(t, nzcv):
    t.e("msr\tcpsr_f, #0x%x" % (nzcv << 28))


def blk_hash(t, lo=0x40, hi=0xc0):
    """Fold the data-area words [lo, hi) into r10 (uses r0, r7, r8)."""
    lab = t.label()
    t.e("add\tr8, r12, #0x%x" % lo, "mov\tr7, #%d" % ((hi - lo) // 4), lab + ":",
        "ldr\tr0, [r8], #4", "MIX\tr0", "subs\tr7, r7, #1", "bne\t" + lab)


def load_regs(t):
    t.e("ldr\tr0, =rinit", "ldmia\tr0, {r0-r8, r14}")


# ---------------------------------------------------------------------------
def v_shift():
    t = T("v_shift", "Barrel shifter: types x amounts x S x carry in, through logical and\n"
          "arithmetic operations; scaled register offsets with the amount-0 encodings.")
    vals = [0, 1, 0x80000000, 0x80000001, 0x7ffffffe, 0xffffffff, 0xaaaaaaaa, 0x55555555,
            0x12345678, 0x0000ffff]
    t.e("ldr\tr5, =0x7fffffff", "ldr\tr6, =0xf0f0f0f0")

    def body(sh):
        lab = t.label()
        t.e("ldr\tr8, =vals", "mov\tr7, #%d" % len(vals), lab + ":", "ldr\tr4, [r8], #4")
        for f in (0x5, 0xA):            # Z and V set, C clear / N and C set
            for op in ("movs\tr0, r4, %s", "mov\tr0, r4, %s", "adcs\tr0, r5, r4, %s",
                       "rscs\tr0, r5, r4, %s", "bics\tr0, r6, r4, %s", "teq\tr6, r4, %s",
                       "cmn\tr5, r4, %s"):
                setf(t, f)
                t.e(op % sh)
                if not op.startswith(("teq", "cmn")):
                    t.e("MIX\tr0")
                t.e("MIXF")
        t.sig()
        t.e("subs\tr7, r7, #1", "bne\t" + lab)

    for sh in ("lsl #1", "lsl #31", "lsl #0", "lsr #1", "lsr #31", "lsr #32", "asr #1",
               "asr #31", "asr #32", "ror #1", "ror #31", "rrx"):
        body(sh)
        t.pool()
    for ty in ("lsl", "lsr", "asr", "ror"):
        lab = t.label()
        t.e("ldr\tr3, =amts", lab + "a:", "ldr\tr2, [r3], #4", "cmp\tr2, #0x5a", "beq\t%sz" % lab)
        body(ty + " r2")
        t.e("b\t%sa" % lab, lab + "z:")
        t.pool()
    # scaled register offsets (bytes, or aligned words)
    t.e("add\tr1, r12, #0x80")
    for rm, flags, ins in ((0x40, 0, "ldrb\tr0, [r1, r2, lsr #32]"),
                           (0x40, 2, "ldrb\tr0, [r1, r2, asr #32]"),
                           (-0x40, 0, "ldrb\tr0, [r1, r2, asr #32]"),
                           (-0x40, 0, "ldrb\tr0, [r1, -r2, asr #32]"),
                           (0x40, 0, "ldrb\tr0, [r1, r2, rrx]"),
                           (0x41, 0, "ldrb\tr0, [r1, -r2, rrx]"),
                           (0x40, 0, "ldr\tr0, [r1, r2, lsl #0]"),
                           (0x20, 0, "ldr\tr0, [r1, -r2, ror #31]"),
                           (0x40, 2, "ldr\tr0, [r1, r2, lsr #32]"),
                           (0x41, 0, "strb\tr6, [r1, r2, rrx]"),
                           (0x40, 0, "str\tr6, [r1, -r2, lsr #3]!")):
        t.e("ldr\tr2, =0x%x" % (rm & 0xffffffff))
        setf(t, flags)
        t.e(ins, "MIX\tr0", "MIX\tr1", "MIXF")
        t.sig()
    blk_hash(t, 0x60, 0x100)
    t.tail += ["vals:\t.word\t" + ", ".join("0x%08x" % v for v in vals),
               "amts:\t.word\t0, 1, 31, 32, 33, 64, 224, 255, 256, 0x1f1, 0xffffff20, 0x80000021, 0x5a"]
    return t, True


def v_imm():
    t = T("v_imm", "Rotated immediates: the carry is bit 31 of the value when the rotation\n"
          "is not 0, and unchanged when it is; every data-processing opcode.")
    # (imm8, rot): (4, 0) and (1, 15) are both 4, (0x80, 0) and (0x08, 14) both
    # 0x80, (0, 0) and (0, 5) both 0
    encs = [(4, 0), (1, 15), (0xff, 0), (0xff, 4), (0x02, 1), (0x80, 0), (0x08, 14), (0xc0, 1),
            (0x01, 1), (0x3f, 3), (0, 0), (0, 5)]
    t.e("ldr\tr4, =0x80000001", "ldr\tr5, =0x7fffffff")
    for op in range(16):
        rn = 0 if op in (0xd, 0xf) else (4 if op % 2 == 0 else 5)
        for imm8, rot in encs:
            for f in (0x5, 0xA):
                setf(t, f)
                t.e(".word\t0x%08x" % (0xE2100000 | op << 21 | rn << 16 | rot << 8 | imm8))
                t.e("MIX\tr0", "MIXF")
        t.sig()
    for op in (0, 2, 4, 5, 0xd, 0xf):       # without S: the flags stay
        rn = 0 if op in (0xd, 0xf) else 4
        setf(t, 0xA)
        t.e(".word\t0x%08x" % (0xE2000000 | op << 21 | rn << 16 | 1 << 8 | 2), "MIX\tr0", "MIXF")
    t.sig()
    return t, True


def v_cond():
    t = T("v_cond", "Each NZCV value against the 15 conditions other than NV, for each\n"
          "instruction class; a failed condition must leave no trace.")
    t.e("mov\tr6, #0", "outer:", "SIG\tr6", "ldr\tr1, =0x7fffffff", "mov\tr2, #1")

    def each(setup, op, record):
        for c in CONDS:
            t.e(*[s.replace("CC", c) for s in setup])
            t.e("msr\tcpsr_f, r6")
            t.e(*[o.replace("CC", c) for o in op])
            t.e(*[r.replace("CC", c) for r in record])
        t.sig()

    restore = []
    for off in (0x78, 0x7c, 0x80, 0x84):
        restore += ["ldr\tr4, =0x%08x" % pattern(off), "str\tr4, [r12, #0x%x]" % off]
    each([], ["addsCC\tr0, r1, r2"], ["MIX\tr0", "MIXF"])
    each(["mov\tr0, #0"], ["bCC\t1f", "orr\tr0, r0, #1", "1:"], ["MIX\tr0"])
    each(["mov\tr0, #0", "mov\tlr, #0"], ["blCC\tvsub"], ["MIX\tr0", "MIX\tlr"])
    each(["mov\tr0, #0", "adr\tr7, 1f"], ["bxCC\tr7", "orr\tr0, r0, #1", "1:"], ["MIX\tr0"])
    each(["mov\tr0, #0"], ["ldrCC\tr0, [r12, #4]"], ["MIX\tr0"])
    each(["mov\tr0, #0", "str\tr0, [r12, #0x40]", "ldr\tr3, =0x11223344"],
         ["strCC\tr3, [r12, #0x40]"], ["ldr\tr0, [r12, #0x40]", "MIX\tr0"])
    each(["mov\tr0, #0", "mov\tr3, #0", "mov\tr4, #0x99", "str\tr0, [r12, #0x44]"],
         ["ldrhCC\tr0, [r12, #6]", "msr\tcpsr_f, r6", "ldrsbCC\tr3, [r12, #7]", "msr\tcpsr_f, r6",
          "strbCC\tr4, [r12, #0x45]"],
         ["MIX\tr0", "MIX\tr3", "ldr\tr0, [r12, #0x44]", "MIX\tr0"])
    each(["mov\tr0, #5", "mov\tr3, #7"], ["mulCC\tr0, r1, r1", "msr\tcpsr_f, r6", "mlaCC\tr3, r1, r1, r2"],
         ["MIX\tr0", "MIX\tr3", "MIXF"])
    each(["mov\tr0, #5", "mov\tr3, #7"], ["umullCC\tr0, r3, r1, r1"], ["MIX\tr0", "MIX\tr3", "MIXF"])
    each(["mov\tr0, #5", "mov\tr3, #7", "add\tr9, r12, #0x80", "ldr\tr4, =0xabcdef01",
          "ldr\tr5, =0x10fedcba"],
         ["ldmiaCC\tr9!, {r0, r3}", "msr\tcpsr_f, r6", "stmdbCC\tr9!, {r4, r5}"],
         ["MIX\tr0", "MIX\tr3", "MIX\tr9", "ldr\tr0, [r12, #0x78]", "MIX\tr0", "ldr\tr0, [r12, #0x7c]",
          "MIX\tr0", "ldr\tr0, [r12, #0x80]", "MIX\tr0", "ldr\tr0, [r12, #0x84]", "MIX\tr0"] + restore)
    each(["mov\tr0, #5", "mov\tr3, #3"], ["movsCC\tr0, r1, lsl r3"], ["MIX\tr0", "MIXF"])
    each([], ["msrCC\tcpsr_f, #0x60000000"], ["MIXF"])
    each(["mov\tr0, #5"], ["mrsCC\tr0, cpsr"], ["MIX\tr0"])
    each(["mov\tr0, #0", "adr\tr7, 1f", "str\tr7, [r12, #0x48]", "add\tr7, r12, #0x48"],
         ["ldrCC\tpc, [r7]", "orr\tr0, r0, #1", "1:"], ["MIX\tr0"])
    t.e("add\tr6, r6, #0x10000000", "cmp\tr6, #0", "bne\touter")
    t.tail += ["vsub:\tadd\tr0, r0, #1", "\tbx\tlr"]
    return t, True


def v_mul():
    t = T("v_mul", "MUL, MLA and UMULL on corner values; the overlapping register forms\n"
          "ARMv4 defines; flags kept.")
    vals = [0, 1, 2, 0xffffffff, 0x80000000, 0x7fffffff, 0x0000ffff, 0x00010000, 0x12345678,
            0xfffffffe, 0x80000001, 0xdeadbeef]
    t.e("mov\tr7, #0", "1:", "ldr\tr8, =vals", "ldr\tr1, [r8, r7, lsl #2]", "mov\tr6, #0",
        "2:", "ldr\tr2, [r8, r6, lsl #2]", "eor\tr3, r1, r2, ror #5")
    setf(t, 0xA)
    t.e("mul\tr0, r1, r2", "MIX\tr0",
        "mla\tr0, r1, r2, r3", "MIX\tr0",
        "umull\tr4, r5, r1, r2", "MIX\tr4", "MIX\tr5",
        "mul\tr0, r2, r2", "MIX\tr0",
        "mov\tr0, r2", "mul\tr0, r1, r0", "MIX\tr0",
        "mov\tr4, r3", "mla\tr4, r1, r2, r4", "MIX\tr4",
        "mov\tr5, r2", "umull\tr4, r5, r1, r5", "MIX\tr4", "MIX\tr5",
        "mov\tr4, r2", "umull\tr4, r5, r1, r4", "MIX\tr4", "MIX\tr5",
        "MIXF", "SIG\tr10",
        "add\tr6, r6, #1", "cmp\tr6, #%d" % len(vals), "bne\t2b",
        "add\tr7, r7, #1", "cmp\tr7, #%d" % len(vals), "bne\t1b")
    t.tail += ["vals:\t.word\t" + ", ".join("0x%08x" % v for v in vals)]
    return t, True


def v_blk():
    t = T("v_blk", "LDM/STM: the four modes, with and without write-back, several lists\n"
          "(the base never in the list); push/pop; stmib sp.")
    for l in ("{r0}", "{r1, r3}", "{r0-r8}", "{r0-r8, r14}", "{r2, r7, r14}"):
        for mode in ("ia", "ib", "da", "db"):
            for w in ("", "!"):
                for ld in ("stm", "ldm"):
                    load_regs(t)
                    t.e("add\tr9, r12, #0x80", "%s%s\tr9%s, %s" % (ld, mode, w, l), "MIX\tr9")
                    for r in ("r0", "r1", "r2", "r3", "r7", "r8", "r14"):
                        t.e("MIX\t" + r)
                    if ld == "stm":
                        blk_hash(t)
                    t.sig()
    load_regs(t)
    t.e("push\t{r0-r8, r14}", "MIX\tsp", "pop\t{r4-r8, r14}", "pop\t{r0-r3}",
        "MIX\tsp", "MIX\tr0", "MIX\tr4", "MIX\tr14", "sub\tsp, sp, #16", "stmib\tsp, {r0, r1}",
        "ldmia\tsp, {r2-r5}", "add\tsp, sp, #16", "MIX\tr3", "MIX\tr4", "MIX\tr5", "MIX\tsp")
    t.sig()
    t.tail += [RINIT]
    return t, True


# ---------------------------------------------------------------------------
# Producers write r3, with V (an address in the data area, so that r3 can
# also be a base) where they can: (name, set-up, producer, gives V)
V = 0x40002040
PRODUCERS = [
    ("ldr_ram", ["ldr\tr1, =0x%x" % V, "str\tr1, [r12, #0xc0]"], ["ldr\tr3, [r12, #0xc0]"], True),
    ("ldr_ram_post", ["ldr\tr1, =0x%x" % V, "str\tr1, [r12, #0xc0]", "add\tr4, r12, #0xc0"],
     ["ldr\tr3, [r4], #4"], True),
    ("ldr_rom", ["ldr\tr4, =vword"], ["ldr\tr3, [r4]"], True),
    ("ldrh_ram", [], ["ldrh\tr3, [r12, #0x42]"], False),
    ("ldrsb_asset", ["ldr\tr4, =ASSET"], ["ldrsb\tr3, [r4, #0x11]"], False),
    ("ldr_asset", ["ldr\tr4, =ASSET"], ["ldr\tr3, [r4, #0x20]"], False),
    ("ldr_mmio", ["ldr\tr4, =MMIO"], ["ldr\tr3, [r4]"], False),
    ("add", ["ldr\tr1, =0x%x" % (V - 0x123), "ldr\tr2, =0x123"], ["add\tr3, r1, r2"], True),
    ("movs_regshift", ["ldr\tr1, =0x%x" % (V >> 2), "mov\tr2, #2"], ["movs\tr3, r1, lsl r2"], True),
    ("mul", ["mov\tr1, #0x40", "ldr\tr2, =0x01000081"], ["mul\tr3, r1, r2"], True),
    ("mla", ["mov\tr1, #0x20", "ldr\tr2, =0x01000081", "ldr\tr4, =0x20001020"],
     ["mla\tr3, r1, r2, r4"], True),
    ("umull_lo", ["mov\tr1, #0x40", "ldr\tr2, =0x01000081"], ["umull\tr3, r4, r1, r2"], True),
    ("umull_hi", ["mov\tr1, #0x80000000", "ldr\tr2, =0x%x" % (V << 1)], ["umull\tr4, r3, r1, r2"], True),
    ("ldm_last", ["ldr\tr1, =0x%x" % V, "str\tr1, [r12, #0xc4]", "add\tr4, r12, #0xc0"],
     ["ldmia\tr4, {r2, r3}"], True),
    ("ldm_first", ["ldr\tr1, =0x%x" % V, "str\tr1, [r12, #0xc0]", "add\tr4, r12, #0xc0"],
     ["ldmia\tr4, {r3, r5}"], True),
    ("base_wb", ["ldr\tr3, =0x%x" % (V - 4)], ["ldr\tr4, [r3, #4]!"], True),
    ("base_wb_post", ["ldr\tr3, =0x%x" % (V - 4)], ["ldrh\tr4, [r3], #4"], True),
    ("ldm_wb", ["ldr\tr3, =0x%x" % (V - 8)], ["ldmia\tr3!, {r4, r5}"], True),
    ("mrs", ["msr\tcpsr_f, #0x90000000"], ["mrs\tr3, cpsr"], False),
]
# Consumers read r3; r7 and r8 are the other operands: (name, code, needs V)
CONSUMERS = [
    ("rn", ["add\tr0, r3, #1"], False),
    ("rm", ["add\tr0, r7, r3"], False),
    ("rm_imm_shift", ["eor\tr0, r7, r3, ror #3"], False),
    ("rs", ["mov\tr0, r7, lsl r3"], False),
    ("rm_regshift", ["adds\tr0, r7, r3, lsr r8"], False),
    ("rn_regshift", ["sub\tr0, r3, r7, lsl r8"], False),
    ("mul_rm", ["mul\tr0, r3, r7"], False),
    ("mul_rs", ["mul\tr0, r7, r3"], False),
    ("mla_rn", ["mla\tr0, r7, r8, r3"], False),
    ("umull", ["umull\tr0, r1, r3, r7"], False),
    ("str_data", ["str\tr3, [r12, #0xd0]"], False),
    ("str_data_regoff", ["mov\tr0, #0xd4", "str\tr3, [r12, r0]"], False),
    ("strh_data", ["strh\tr3, [r12, #0xd8]"], False),
    ("stm_data", ["add\tr0, r12, #0xe0", "stmia\tr0, {r2, r3}"], False),
    ("stm_data_only", ["add\tr0, r12, #0xe8", "stmia\tr0, {r3}"], False),
    ("cmp", ["cmp\tr3, r7"], False),
    ("ldr_regoff", ["ldrb\tr0, [r12, r3, lsr #24]"], False),
    ("msr", ["msr\tcpsr_f, r3"], True),
    ("ldr_base", ["ldr\tr0, [r3]"], True),
    ("ldr_base_wb", ["ldrb\tr0, [r3, #1]!"], True),
    ("str_base", ["str\tr7, [r3, #0x80]"], True),
    ("ldm_base", ["ldmia\tr3, {r0, r1}"], True),
]


def v_deps(k, producers, bl=False):
    t = T("v_deps%d" % k, "Register dependences: each producer of r3, then each consumer position,\n"
          "straight after and with one instruction between.")
    for pname, setup, prod, gives_v in producers:
        for cname, cons, needs_v in CONSUMERS:
            if needs_v and not gives_v:
                continue
            for gap in (False, True):
                t.e("ldr\tr7, =0x00000013", "mov\tr8, #3", "mov\tr2, #0x55", "mov\tr0, #0", "mov\tr1, #0")
                t.e(*setup)
                t.e(*prod)
                if gap:
                    t.e("mov\tr9, #0")
                t.e(*cons)
                t.e("MIX\tr0", "MIX\tr1", "MIX\tr3", "MIXF", "msr\tcpsr_f, #0")
            t.sig()
    if bl:      # the link register, used at once
        for use in ("add\tr0, lr, #4", "str\tlr, [r12, #0xd0]", "mov\tr0, lr, lsl r8",
                    "mul\tr0, lr, r7", "cmp\tlr, r7", "ldr\tr0, [lr]"):
            lab = t.label()
            t.e("mov\tr0, #0", "bl\t" + lab, lab + ":", use, "MIX\tr0", "MIX\tlr", "MIXF")
        t.sig()
    blk_hash(t, 0xc0, 0x100)
    t.tail += ["vword:\t.word\t0x%x" % V]
    return t, False


def v_wb():
    t = T("v_wb", "Rd == Rn with write-back (a load keeps the loaded value, a store the\n"
          "old base, as on the ARM7TDMI); Rm == Rn and Rd == Rm; the T forms.")
    for op, sz in (("ldr", 4), ("str", 4), ("ldrb", 1), ("strb", 1), ("ldrh", 2), ("strh", 2),
                   ("ldrsb", 1), ("ldrsh", 2)):
        for mode in ("[r3, #%d]!", "[r3], #%d", "[r3, #-%d]!", "[r3], #-%d",
                     "[r3, r2]!", "[r3], r2", "[r3, -r2]!", "[r3], -r2"):
            am = mode % (4 * sz) if "%" in mode else mode
            t.e("add\tr3, r12, #0x80", "mov\tr2, #%d" % (2 * sz), op + "\tr3, " + am, "MIX\tr3")
            blk_hash(t, 0x70, 0x90)
        t.sig()
    for ins in ("ldr\tr3, [r3, -r3]!", "ldrb\tr3, [r3, -r3]", "ldrh\tr4, [r3, -r3]!",
                "ldr\tr4, [r3, r4]!", "ldr\tr4, [r3], r4", "ldrsh\tr4, [r3, r4]!",
                "ldrt\tr3, [r3], #4", "ldrbt\tr3, [r3], #-1", "strt\tr3, [r3], #4",
                "strbt\tr3, [r3], #1", "ldrt\tr0, [r3], r4", "strbt\tr0, [r3], -r4, lsl #1"):
        t.e("add\tr3, r12, #0x80", "mov\tr4, #8", "mov\tr0, #0x77", ins, "MIX\tr3", "MIX\tr4", "MIX\tr0")
        blk_hash(t, 0x70, 0x90)
        t.sig()
    return t, False


def v_align():
    t = T("v_align", "Loads at every byte offset from RAM, ROM, the asset window and the\n"
          "peripheral; unaligned STR and STRH, read back.")
    t.e("ldr\tr4, =ASSET", "ldr\tr5, =rodata", "ldr\tr6, =MMIO", "add\tr7, r12, #0x20")
    for base in ("r7", "r5", "r4", "r6"):
        for off in range(8):
            for op in ("ldr", "ldrh", "ldrsh", "ldrb", "ldrsb"):
                t.e("%s\tr0, [%s, #%d]" % (op, base, off), "MIX\tr0")
            neg = "-" if base in ("r7", "r5") else ""
            t.e("mov\tr1, #%d" % off, "ldrh\tr0, [%s, r1]" % base, "MIX\tr0",
                "ldrsh\tr0, [%s, %sr1]" % (base, neg), "MIX\tr0", "ldr\tr0, [%s, %sr1]" % (base, neg), "MIX\tr0")
        t.sig()
    t.e("ldr\tr4, =ASSET + 0x3f8")      # the last bytes of the 1 KiB asset image
    for off in range(8):
        for op in ("ldrb", "ldrsb", "ldrh", "ldrsh", "ldr"):
            t.e("%s\tr0, [r4, #%d]" % (op, off), "MIX\tr0")
    t.sig()
    for off in range(4):
        t.e("ldr\tr1, =0xa1b2c3d4", "add\tr2, r12, #0x60", "str\tr1, [r2, #%d]" % off,
            "strh\tr1, [r2, #%d]" % (off + 4), "mov\tr3, #%d" % (off + 8), "str\tr1, [r2, r3]",
            "add\tr3, r3, #4", "strh\tr1, [r2, r3]")
        blk_hash(t, 0x5c, 0x78)
        t.sig()
    t.e("add\tr3, r12, #0x41", "ldr\tr0, [r3], #4", "MIX\tr0", "MIX\tr3",
        "ldrh\tr0, [r3, #2]!", "MIX\tr0", "MIX\tr3", "ldrsh\tr0, [r3, #-2]!", "MIX\tr0", "MIX\tr3")
    t.tail += ["rodata:\t.word\t0x80ff7f01, 0xfe0280c3, 0x11223344, 0x8899aabb"]
    return t, False


def v_blkx():
    t = T("v_blkx", "LDM/STM with the base in the list: lowest, middle, highest and alone,\n"
          "all four modes, with and without write-back (ARM7TDMI results).")
    for base, l in (("r0", "{r0, r2, r5}"), ("r2", "{r0, r2, r5}"), ("r5", "{r0, r2, r5}"),
                    ("r4", "{r4}"), ("r14", "{r0-r8, r14}"), ("r1", "{r0-r8, r14}")):
        for mode in ("ia", "ib", "da", "db"):
            for w in ("", "!"):
                for ld in ("stm", "ldm"):
                    load_regs(t)
                    t.e("add\t%s, r12, #0x80" % base, "%s%s\t%s%s, %s" % (ld, mode, base, w, l))
                    for r in ("r0", "r1", "r2", "r4", "r5", "r8", "r14"):
                        t.e("MIX\t" + r)
                    blk_hash(t)
                    t.sig()
    t.tail += [RINIT]
    return t, False


def v_mmio():
    t = T("v_mmio", "Peripheral accesses under every NZCV and condition: failed reads must\n"
          "not pop and failed writes must not push; offsets, write-back, sizes.")
    t.e("ldr\tr5, =MMIO", "mov\tr6, #0", "outer:")
    for c in CONDS[:-1]:
        t.e("mov\tr0, #0x33", "msr\tcpsr_f, r6", "ldr%s\tr0, [r5, #4]" % c, "MIX\tr0",
            "msr\tcpsr_f, r6", "str%s\tr6, [r5, #0x10]" % c,
            "mov\tr1, #0x14", "msr\tcpsr_f, r6", "ldr%s\tr0, [r5, r1]" % c, "MIX\tr0")
    t.sig()
    t.e("add\tr6, r6, #0x10000000", "cmp\tr6, #0", "bne\touter")
    t.pool()
    t.e("ldr\tr7, =0x12345678", "ldr\tr0, [r5, #0x14]", "MIX\tr0", "mov\tr1, #0x10", "str\tr7, [r5, r1]",
        "ldr\tr0, [r5, #0x14]", "MIX\tr0", "strb\tr7, [r5, #0x10]", "strh\tr7, [r5, #0x10]",
        "ldr\tr0, [r5, #0x14]", "MIX\tr0", "add\tr4, r5, #0x10", "str\tr7, [r4], #4", "MIX\tr4",
        "ldr\tr0, [r4, #-4]!", "MIX\tr0", "MIX\tr4", "mov\tr4, r5", "ldr\tr4, [r4]", "MIX\tr4",
        "ldrb\tr0, [r5, #3]", "MIX\tr0", "ldrh\tr0, [r5, #2]", "MIX\tr0", "ldrsh\tr0, [r5]", "MIX\tr0",
        "ldrsb\tr0, [r5, #1]", "MIX\tr0", "ldr\tr0, [r5, #0xfc]", "MIX\tr0", "str\tr0, [r5, #0xfc]",
        "mov\tr1, #0x14", "ldr\tr0, [r5, r1]!", "MIX\tr0", "MIX\tr5")
    t.sig()
    return t, False


def v_nv():
    t = T("v_nv", "The NV condition: never executed on ARMv4, whatever the encoding\n"
          "(ARMv5 gives some of these meanings of their own).")
    t.e("ldr\tr1, =0x10000000", "mov\tr0, #0x11", "mov\tr2, #0x22")
    for w in (0xF0810002, 0xF3A00001, 0xF1B00001, 0xF5910000, 0xF58C0000, 0xF1DC00B0,
              0xF0000291, 0xF0800291, 0xF89C0003, 0xF88C0003, 0xFA000010, 0xFB000010,
              0xF12FFF11, 0xF10F0000, 0xF128F001, 0xF321F010, 0xFF000000, 0xFE000000,
              0xF1A0F00E, 0xF1000090, 0xF6000010, 0xF8BD8000, 0xF4910000, 0xF7D2F003):
        t.e(".word\t0x%08x" % w, "MIX\tr0", "MIX\tr2", "MIXF")
    t.sig()
    return t, False


def v_unpred():
    t = T("v_unpred", "Register overlaps ARMv4 leaves UNPREDICTABLE that the core runs as\n"
          "the ARM7TDMI does: MUL/MLA Rd == Rm, UMULL RdLo/RdHi == Rm.")
    for a, b in ((3, 5), (0xffffffff, 0x80000001), (0x12345678, 0x9abcdef0)):
        t.e("ldr\tr1, =0x%x" % a, "ldr\tr2, =0x%x" % b,
            "mov\tr3, r1", ".word\t0xe0030293", "MIX\tr3",          # mul r3, r3, r2
            "mov\tr3, r1", ".word\t0xe0231293", "MIX\tr3",          # mla r3, r3, r2, r1
            "mov\tr3, r1", ".word\t0xe0843293", "MIX\tr3", "MIX\tr4",   # umull r3, r4, r3, r2
            "mov\tr4, r1", ".word\t0xe0843294", "MIX\tr3", "MIX\tr4",   # umull r3, r4, r4, r2
            "mov\tr4, r2", "umull\tr3, r4, r1, r4", "MIX\tr3", "MIX\tr4")
        t.sig()
    return t, False


def main():
    out = sys.argv[1]
    os.makedirs(out, exist_ok=True)
    tests = [v_shift(), v_imm(), v_cond(), v_mul(), v_blk(),
             v_deps(1, PRODUCERS[0:4]), v_deps(2, PRODUCERS[4:8]), v_deps(3, PRODUCERS[8:12]),
             v_deps(4, PRODUCERS[12:16]), v_deps(5, PRODUCERS[16:], bl=True),
             v_wb(), v_align(), v_blkx(), v_mmio(), v_nv(), v_unpred()]
    iss = []
    for t, ok in tests:
        open(os.path.join(out, t.name + ".S"), "w").write(t.text())
        if ok:
            iss.append(t.name)
    open(os.path.join(out, "iss.txt"), "w").write("\n".join(iss) + "\n")
    print("vgen: %d tests in %s (%d also against Unicorn)" % (len(tests), out, len(iss)))


if __name__ == "__main__":
    main()
