#!/usr/bin/env python3
"""Random ISA test for the BupChip CPU subset, as assembler on stdout.

  gen_random.py SEED [N] > test.S        N operations (default 200)

The mix is weighted like the measured Misery_F mix (docs/BUPCHIP.md): data
processing (register / immediate / shift by register), LDRH/STRH/LDRSB/LDRSH,
LDR/STR(B), MUL/MLA, a little UMULL and LDM/STM, forward conditional
branches and BL/BX, 13% conditional. After every operation the destination
and the flags go to the signature (r11); the end is a FAULT write of 0xAA.
run_isa.sh links it with link.ld and compares the reference RTL with
Unicorn. The same SEED and N always give the same program.

Left out, because ARMv4T and the ARMv5TE golden model differ or the
architecture leaves them UNPREDICTABLE, and CoreTone does not use them:
unaligned word/halfword accesses, MUL Rd == Rm, flag-setting multiplies,
PC as an operand or destination, writeback with Rn in the list or Rn == Rd.
Register roles: r0-r9 data, r10 scratch, r11 signature pointer, r12 data
area base (0x40002000, 256 bytes), r13 stack.
"""
import random, sys

seed = int(sys.argv[1]); n = int(sys.argv[2]) if len(sys.argv) > 2 else 200
R = random.Random(seed)
DATA = [f"r{i}" for i in range(10)]
CONDS = ["eq", "ne", "cs", "cc", "mi", "pl", "vs", "vc", "hi", "ls", "ge", "lt", "gt", "le"]
DP3 = ["and", "eor", "sub", "rsb", "add", "adc", "sbc", "rsc", "orr", "bic"]
DP2 = ["mov", "mvn"]
CMP = ["cmp", "cmn", "tst", "teq"]
SH = ["lsl", "lsr", "asr", "ror"]

def r(): return R.choice(DATA)
def cond(): return R.choice(CONDS) if R.random() < 0.13 else ""
def imm8r():                                   # an encodable rotated immediate
    v, rot = R.randrange(256), 2 * R.randrange(16)
    return ((v >> rot) | (v << (32 - rot))) & 0xffffffff
def op2():
    k = R.random()
    if k < 0.40: return r()
    if k < 0.85:
        s = R.choice(SH + ["rrx"])
        if s == "rrx": return f"{r()}, rrx"
        amt = R.randrange(1, 32) if s in ("lsl", "ror") else R.randrange(1, 33)
        return f"{r()}, {s} #{amt}"
    return f"{r()}, {R.choice(SH)} {r()}"       # shift by register, any amount 0-255

out = []
def emit(s): out.append("\t" + s)
def sig(reg): emit(f"str\t{reg}, [r11], #4")
def sigf():
    emit("mov\tr10, #0"); emit("orrmi\tr10, r10, #8"); emit("orreq\tr10, r10, #4")
    emit("orrcs\tr10, r10, #2"); emit("orrvs\tr10, r10, #1"); sig("r10")

print(f"@ generated by gen_random.py {seed} {n}")
print("\t.syntax unified\n\t.arm\n\t.cpu arm7tdmi\n\t.section .vectors, \"ax\"\n\t.global _start")
print("_start:\tb\treset\n" + "\tb\t.\n" * 7 + "\t.text\nreset:")
for s in ["mrs\tr0, cpsr", "bic\tr0, r0, #31", "orr\tr0, r0, #0xd3", "msr\tcpsr_c, r0",
          "ldr\tsp, =__stack_top", "ldr\tr11, =__sig_start", "ldr\tr12, =0x40002000"]:
    emit(s)
for i in range(64):                            # deterministic data area
    emit(f"ldr\tr0, ={R.getrandbits(32):#010x}"); emit(f"str\tr0, [r12, #{4 * i}]")
for d in DATA:
    emit(f"ldr\t{d}, ={R.getrandbits(32):#010x}")
emit(f"{'cmn' if R.random() < .5 else 'cmp'}\tr0, r1")   # random initial flags
emit("b\t1f"); emit(".ltorg"); out.append("1:")

label = 0
for i in range(n):
    if i % 64 == 63:
        label += 1; emit(f"b\tpool{label}"); emit(".ltorg"); out.append(f"pool{label}:")
    k = R.random(); c = cond()
    if k < 0.27:
        o = R.choice(DP3); s = "s" if R.random() < 0.3 else ""; d = r()
        emit(f"{o}{s}{c}\t{d}, {r()}, {op2()}"); sig(d); sigf()
    elif k < 0.33:
        o = R.choice(DP2); s = "s" if R.random() < 0.3 else ""; d = r()
        emit(f"{o}{s}{c}\t{d}, {op2()}"); sig(d); sigf()
    elif k < 0.40:
        emit(f"{R.choice(CMP)}{c}\t{r()}, {op2()}"); sigf()
    elif k < 0.48:
        o = R.choice(DP3 + DP2); d = r(); s = "s" if R.random() < 0.3 else ""
        emit(f"{o}{s}{c}\t{d}, #{imm8r():#x}" if o in DP2 else f"{o}{s}{c}\t{d}, {r()}, #{imm8r():#x}")
        sig(d); sigf()
    elif k < 0.73:                               # halfword / signed transfers
        o = R.choice(["ldrh", "ldrsh", "ldrsb", "strh", "ldrh", "ldrsh"])
        al = 1 if o == "ldrsb" else 2
        off = R.randrange(0, 256 // al) * al; d = r()
        if R.random() < 0.3:                     # register offset
            emit(f"mov\tr10, #{off}"); emit(f"{o}{c}\t{d}, [r12, r10]")
        else:
            emit(f"{o}{c}\t{d}, [r12, #{off}]")
        if o.startswith("ldr"): sig(d)
        else: emit(f"ldr\tr10, [r12, #{off & ~3}]"); sig("r10")
    elif k < 0.87:                               # word / byte transfers
        o = R.choice(["ldr", "str", "ldrb", "strb", "ldr"])
        al = 4 if o in ("ldr", "str") else 1
        off = R.randrange(0, 256 // al) * al; d = r()
        if R.random() < 0.3 and al == 4:
            emit(f"mov\tr10, #{off // 4}"); emit(f"{o}{c}\t{d}, [r12, r10, lsl #2]")
        else:
            emit(f"{o}{c}\t{d}, [r12, #{off}]")
        if o.startswith("ldr"): sig(d)
        else: emit(f"ldr\tr10, [r12, #{off & ~3}]"); sig("r10")
    elif k < 0.95:                               # MUL / MLA (Rd != Rm), rare UMULL
        if R.random() < 0.05:
            lo, hi, m = R.sample(DATA, 3)
            emit(f"umull{c}\t{lo}, {hi}, {m}, {r()}"); sig(lo); sig(hi)
        else:
            d, m = R.sample(DATA, 2)
            if R.random() < 0.5: emit(f"mul{c}\t{d}, {m}, {r()}")
            else: emit(f"mla{c}\t{d}, {m}, {r()}, {r()}")
            sig(d)
    elif k < 0.965:                              # LDM/STM through the stack
        regs = sorted(R.sample(DATA, R.randrange(1, 5)), key=lambda x: int(x[1:]))
        emit(f"push\t{{{', '.join(regs)}}}")
        regs2 = sorted(R.sample(DATA, len(regs)), key=lambda x: int(x[1:]))
        emit(f"pop\t{{{', '.join(regs2)}}}")
        for x in regs2: sig(x)
    else:                                        # forward conditional branch / BL
        label += 1
        if R.random() < 0.3:
            emit(f"bl\tsub{label}"); emit(f"b\tafter{label}")
            out.append(f"sub{label}:"); emit(f"add\tr0, r0, #{label}"); emit("bx\tlr")
            out.append(f"after{label}:"); sig("r0")
        else:
            emit(f"b{R.choice(CONDS)}\tskip{label}")
            for _ in range(R.randrange(1, 3)):
                d = r(); emit(f"eor\t{d}, {d}, #{imm8r():#x}")
            out.append(f"skip{label}:")
            for d in DATA: sig(d)
for d in DATA: sig(d)
sigf()
print("\n".join(out))
print("\tldr\tr0, =__sig_start\n\tsub\tr0, r11, r0\n\tldr\tr1, =0xE0009000\n\tstr\tr0, [r1, #0x10]")
print("\tmov\tr0, #0xaa\n\tstr\tr0, [r1, #0x1c]\n\tb\t.\n\t.ltorg")
